# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GRIP
email: wyattleegarland@gmail.com
description: > 
  A ruined sentry. A thirsty goblin. A spoiled wasp. What kind of world will be created with the union of their fates? Unravel the tale of these 3 through the tattered landscape of Wyatt Garland's GRIP.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://grip-comic.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb

# Build settings
markdown: kramdown
